server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: aws
  profiles:
    include:
    - aws

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  output:
    ansi:
      enabled: always
      
        
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: honeybee
    password: honeybee123
    url: jdbc:mysql://localhost:3306/honeybee

  jpa:
    hibernate:
      ddl-auto: none #create update none
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  


file:
  absolutePath: c:/portfolio/honeybee/src/main/resources/static/temp/