server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  output:
    ansi:
      enabled: always
<<<<<<< HEAD

=======
      
>>>>>>> d595a556f185b790e9148135e6a10f2318a3ff41
  jpa:
    hibernate:
      ddl-auto: none #create update none
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
<<<<<<< HEAD
  

=======
>>>>>>> d595a556f185b790e9148135e6a10f2318a3ff41
