server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: honeybee
    password: honeybee123
    url: jdbc:mysql://localhost:3306/honeybee

  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true